services:
  rails-app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
    networks:
      - default
    ports:
      - 4567:4567
    depends_on:
      - redis
      - postgres

  redis:
    image: redis:7.2
    restart: unless-stopped
    networks:
      - default
    volumes:
      - redis-data:/data

  postgres:
    image: postgres:16.1
    restart: unless-stopped
    networks:
      - default
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres

volumes:
  redis-data:
  postgres-data:
